### ISSUE TITLE
Correct Nginx/PHP-FPM connections

### ISSUE THREAD

**Issue by misiman** [dvershinin/NginxConfig#2]
Hi Danila,

I added a comment to your tutorial:

https://www.getpagespeed.com/server-setup/nginx-and-php-fpm-what-my-permissions-should-be

... but it does not appear to have posted, so I'm trying here instead.

In relation to your (Debian) configs:

What should user and group be set to in /etc/php-fpm.d/example.com.conf?

user = www-data 
group = www-data
listen.owner = example
listen.group = example

And the user and group in /etc/nginx/nginx.conf?

user: www-data

Maybe I've misunderstood, because it appears that the user/group and listen.owner/group can be set to either "example" or "www-data" and it still works?

It would appear this is incorrect and/or a security issue. If not, can you further explain the relationship between the Nginx and PHP-FPM users/groups.

Many thanks,
David

**Comment by dvershinin** [comment]
David,

I think it's pretty clear what my recommendation was. It is at the beginning of the article:

```
listen = /var/run/php-fpm/example.com.sock
listen.owner = example
listen.group = example
listen.mode = 0660
```

I did say, among other things "Do not use www-data or nginx as website user. This is wrong and will lead to more troubles!". So please read carefully.

If it works with `www-data` it only means you haven't follow through all the steps / chmod is wrong, etc.

**Comment by misiman** [comment]
Ok,

Thanks for your reply.

I am reasonably competent and did read your article carefully, but didn't see a specific reference as to how the PHP-FPM user/group (not listen.owner/group) should be set.

Other than that, I'm not sure what element of the config has gone wrong. Can you help by clarifying whether the following is correct or, if not, what it should be for a Debian system:

/etc/nginx/nginx.conf
user: www-data

/etc/php-fpm.d/example.com.conf
user = www-data
group = www-data
listen.owner = example
listen.group = example

Thanks

**Comment by dvershinin** [comment]
> didn't see a specific reference as to how the PHP-FPM user/group (not listen.owner/group) should be set.

Sorry about that. I've updated the post. It really should be `example` for *both* socket listen options and user/group options.

Incorrect:

```
user = www-data
group = www-data
listen.owner = example
listen.group = example
```

Correct:

```
user = example
group = example
listen.owner = example
listen.group = example
```

**Comment by misiman** [comment]
Perfect, thanks for the clarification.

David
